#!/bin/bash
# Backup
cp build_apk.sh README.md /tmp/

# Reset
cd ..
rm -rf user-workspace
git clone https://github.com/enriquefnt/blackboxai-1742564595470.git user-workspace
cd user-workspace

# Clean
rm -rf *
rm -f .*

# Restore
cp /tmp/build_apk.sh .
cp /tmp/README.md .
chmod +x build_apk.sh

# Git config
git config --global user.email "enriquefnt@gmail.com"
git config --global user.name "enriquefnt"

# Push
git add .
git commit -m "Reset"
git push -f